In [2]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import cv2


In [4]:
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76


In [5]:
def RGB2HEX(color):
    return "#{:02x}{:02x}{:02x}".format(int(color[0]), int(color[1]), int(color[2]))


In [6]:
#gets image and returns it in rgb
def get_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    return image


In [7]:
#converts image to 2d to feed to kmeans
def flatten(modified_image):
    modified_image = modified_image.reshape(modified_image.shape[0]*modified_image.shape[1], 3)
    return modified_image


In [9]:
#inputing the image file and then flattening it 
image = get_image('pikachu.jpg')
modified_image = flatten(image)


In [14]:
#numbers of colors we want to identify
number_of_colors = 4


In [15]:
clf = KMeans(n_clusters = number_of_colors)
labels = clf.fit_predict(modified_image)

counts = Counter(labels)

center_colors = clf.cluster_centers_

ordered_colors = [center_colors[i] for i in counts.keys()]

hex_colors = [RGB2HEX(ordered_colors[i]) for i in counts.keys()]
rgb_colors = [ordered_colors[i] for i in counts.keys()]


In [16]:
hex_colors

['#12091a', '#f2cc4a', '#6c3333', '#e1d47f']

In [17]:
rgb_colors

[array([18.40494738,  9.42131173, 26.81163373]),
 array([242.09606978, 204.86764796,  74.95175344]),
 array([108.53217582,  51.69115582,  51.91148915]),
 array([225.31956866, 212.50049323, 127.19507117])]

In [19]:
image.shape

(1280, 1280, 3)